Reapply TEMPLATE's mega-linter.yml

diff --git a/.github/workflows/mega-linter.yml b/.github/workflows/mega-linter.yml
--- a/.github/workflows/mega-linter.yml
+++ b/.github/workflows/mega-linter.yml
@@ -3,11 +3,8 @@
 # yamllint disable rule:line-length
 # cSpell:ignore Devskim's, noprofile, norc, rasa, stefanzweifel
 # checkov:skip=CKV2_GHA_1:Ensure top-level permissions are not set to write-all
-
-# MegaLinter GitHub Action configuration file
-# More info at https://megalinter.io
 ---
-name: mega-linter # added by @rasa
+name: MegaLinter
 
 # Trigger mega-linter at every push. Action will also be visible from Pull
 # Requests to main
@@ -45,7 +42,6 @@ name: mega-linter # added by @rasa
           - "true"
         default: "true"
   # </@rasa>
-
 # Comment env block if you do not want to apply fixes
 env:
   # Apply linter fixes configuration
@@ -60,7 +56,7 @@ env:
 
   # If APPLY_FIXES is used, defines if the fixes are directly committed (commit)
   # or posted in a PR (pull_request)
-  APPLY_FIXES_MODE: commit # testing `commit` per https://github.com/oxsecurity/megalinter/pull/2957#pullrequestreview-1632090673
+  APPLY_FIXES_MODE: commit
 
 concurrency:
   group: ${{ github.ref }}-${{ github.workflow }}
@@ -71,11 +67,10 @@ jobs:
     name: MegaLinter
     runs-on: ubuntu-latest
     # <@rasa>
-    defaults:
-      run:
-        shell: bash --noprofile --norc -v -x {0}
+    # defaults:
+    #   run:
+    #     shell: bash --noprofile --norc -v -x {0}
     # </@rasa>
-
     # Give the default GITHUB_TOKEN write permission to commit and push, comment
     # issues & post new PR; remove the ones you do not need
     permissions:
@@ -86,7 +81,7 @@ jobs:
     steps:
       # Git Checkout
       - name: Checkout Code
-        uses: actions/checkout@v4 # changed by @rasa
+        uses: actions/checkout@v4.1.1 # was v4, changed by @rasa
         with:
           token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
 
@@ -94,38 +89,27 @@ jobs:
           # improve performance
           fetch-depth: ${{ inputs.fetch_depth }} # added by @rasa
           show-progress: false # added by @rasa
-
       # <@rasa>
-      # # Attempting to fix Devskim's:
-      # #   fatal: detected dubious ownership in repository at '/github/workspace/.git'
-      # # but it doesn't appear to work
-      # - name: RUN git config global add safe.directory "*"
-      #   run: |
-      #     sudo chown -Rc "${UID}" .git/ /github/workspace/.git
-      #     sudo git config --global --add safe.directory "*"
-      #     sudo git config --global --add safe.directory "/github/workspace/.git"
-      #     # git config --show-origin --list | sort
-      #     # git ls-files -s --eol
-      #     # ls /github/workspace || true
-
       - name: output debug vars
         run: |
           cat <<-EOF
           inputs=${{ toJSON(inputs) }}
           EOF
       # </@rasa>
+
       # MegaLinter
       - name: MegaLinter
 
         # You can override MegaLinter flavor used to have faster performances
         # More info at https://megalinter.io/flavors/
-        uses: oxsecurity/megalinter@v7.5.0 # changed by @rasa
+        uses: oxsecurity/megalinter@v7.5.0 # changed from v7 by @rasa
 
         id: ml
 
         # All available variables are described in documentation
         # https://megalinter.io/configuration/
         env:
+
           # Validates all source when push on main, else just the git diff with
           # main. Override with true if you always want to lint all sources
           #
@@ -140,7 +124,7 @@ jobs:
           #   }}
           VALIDATE_ALL_CODEBASE: >-
             ${{
-              inputs.validate_all_codebase == 'true' ||
+              inputs.validate_all_codebase == 'true' || # added by @rasa
               github.event_name == 'push' &&
               contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)
             }}
@@ -156,15 +140,12 @@ jobs:
       # Upload MegaLinter artifacts
       - name: Archive production artifacts
         uses: actions/upload-artifact@v3
-        # <@rasa>
-        if: always()
-        # </@rasa>
+        if: success() || failure() # changed by @rasa: was ${{ success() }} || ${{ failure() }} 
         with:
           name: MegaLinter reports
           path: |
             megalinter-reports
             mega-linter.log
-
       # <@rasa>
       - name: Remove production artifacts
         continue-on-error: true
@@ -172,7 +153,6 @@ jobs:
           sudo chown -Rc $UID megalinter-reports mega-linter.log
           sudo chmod +w megalinter-reports mega-linter.log
           sudo rm -fr megalinter-reports mega-linter.log
-
       # - name: USES crazy-max/ghaction-dump-context@v2.1.0
       #   uses: crazy-max/ghaction-dump-context@v2.1.0
 
@@ -181,7 +161,7 @@ jobs:
           cat <<-EOF
           steps.ml.outputs=${{ toJSON(steps.ml.outputs) }}
           EOF
-
+      # </@rasa>
       # Set APPLY_FIXES_IF var for use in future steps
       - name: Set APPLY_FIXES_IF var
         run: |
@@ -210,18 +190,12 @@ jobs:
             (!contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref))
           }}" >> "${GITHUB_ENV}"
 
-      # - name: USES crazy-max/ghaction-dump-context@v2.1.0
-      #   uses: crazy-max/ghaction-dump-context@v2.1.0
-      # </@rasa>
-
       # Create pull request if applicable
       # (for now works only on PR from same repository, not from forks)
       - name: Create Pull Request with applied fixes
         uses: peter-evans/create-pull-request@v5
         id: cpr
-        # <@rasa>
         if: env.APPLY_FIXES_IF_PR == 'true'
-        # </@rasa>
         with:
           token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
           commit-message: "[MegaLinter] Apply linters automatic fixes"
@@ -229,9 +203,7 @@ jobs:
           labels: bot
 
       - name: Create PR output
-        # <@rasa>
         if: env.APPLY_FIXES_IF_PR == 'true'
-        # </@rasa>
         run: |
           echo "PR Number - ${{ steps.cpr.outputs.pull-request-number }}"
           echo "PR URL - ${{ steps.cpr.outputs.pull-request-url }}"
@@ -239,16 +211,12 @@ jobs:
       # Push new commit if applicable
       # (for now works only on PR from same repository, not from forks)
       - name: Prepare commit
-        # <@rasa>
         if: env.APPLY_FIXES_IF_COMMIT == 'true'
-        # </@rasa>
         run: sudo chown -Rc $UID .git/
 
       - name: Commit and push applied linter fixes
         uses: stefanzweifel/git-auto-commit-action@v4
-        # <@rasa>
         if: env.APPLY_FIXES_IF_COMMIT == 'true'
-        # </@rasa>
         with:
           branch: >-
             ${{
@@ -259,4 +227,3 @@ jobs:
           commit_message: "[MegaLinter] Apply linters fixes"
           commit_user_name: megalinter-bot
           commit_user_email: nicolas.vuillamy@ox.security
-# eof
